### PR TITLE
Updates for proper P(U|x) calculations

### PR DESCRIPTION
**Pull request by profxj**
Update the normalization of the offset functions and
enabled a proper handling of P(U)>0.

### CODE REVIEW

**Comment by KshitijAggarwal** [comment]
The aim of `P_U_x.ipynb` is to show the impact of non zero unseen prior, right? and then calculating the unseen posterior from it. If so, it might be better to use the same dummy FRB for both notebooks.

**Comment by profxj** [comment]
just an example.  And a bit better than the other because
the host association is 'less complicated'.

**Review by KshitijAggarwal — APPROVED** [review]
Looks good.

**Comment by profxj** [comment]
merging!

**Pull request merged**
